# Este es un archivo de configuración de ejemplo de Supabase.
# Se utiliza para configurar tu proyecto de Supabase para el desarrollo local.
#
# Para más información, visita https://supabase.com/docs/guides/cli/config

project_id = "gomeraway-wayfinder-main"

[api]
port = 54321
schemas = ["public", "storage", "graphql"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

# Configuración para la función que crea la sesión de checkout de Stripe (Suscripciones).
[functions.create-checkout-session]
verify_jwt = true
import_map = "import_map.json"

# Configuración para la función que maneja los webhooks de Stripe.
[functions.stripe-webhook]
verify_jwt = false
import_map = "import_map.json"

# Configuración para la función que crea la sesión de checkout para Reservas.
[functions.create-booking-checkout]
verify_jwt = true
import_map = "import_map.json"
